notifications:
  email: false
  hipchat:
    - secure: "aUQBYlJIV/aS5DjhNFN/2E0+Q0mUKRmbREFfPNgCmunX2Kj0V7nIxbTcosF5Oa7ZuMF22F3v6S/g5ysu/RuW39/fUjBfWu2vfeZ7s/mNd53DVxmb47Bwyjj84G+FsWirgiuHU6HnItmcArydu/kzmgzeNATH7cYqvOK0CBeWwVs="
language: php
php:
  - 5.4
  - 5.5
before_script:
 - composer install
script: sh scripts/test.sh
after_script:
  - php bin/coveralls